name: Test 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EmbarkStudios/cargo-deny-action@v1.1.0
        with:
          log-level: warn
          command: check
          arguments: --all-features

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: cargo test --all --verbose
